apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-geme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-geme
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-geme
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-geme
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-geme
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xhuo-tenant/rhtap-demo-app/hacbs-test-project-geme@sha256:7ede0075927b431b71ef31e66eec9593b592274818cffae2c12af94ced88b313
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
